/**
 * Scoring utilities for Snail's Trail.
 * Penalties, bonuses, and difficulty ranges are loaded from scoring-params.json
 * (generated by scripts/precompute-embeddings.js).
 */

import { isHub } from '../data/hubs.js';
import { getGameDateStr } from './seed.js';
import scoringParamsJson from '../data/scoring-params.json';

// Scoring parameters generated by scripts/precompute-embeddings.js.
// Merge against defaults so missing keys degrade gracefully.
const DEFAULTS = {
  sniffPenalty: { easy: 6, medium: 16, hard: 20 },
  scoutPenalty: { easy: 15, medium: 42, hard: 50 },
  hopSavedBase: 28,
  hopSavedEscalation: 9,
  showMorePenalty: { easy: 0, medium: 5, hard: 10 },
  simRanges: { easy: [0.49, 0.55], medium: [0.46, 0.49], hard: [0.41, 0.46] },
};
const scoringParams = { ...DEFAULTS, ...scoringParamsJson };

export const DIFFICULTY_MAX = { easy: 60, medium: 80, hard: 100 };

// Global normalization range for hop scoring.
// Represents the practical gameplay similarity floor/ceiling for bge-small-en-v1.5.
// SCORING_SIM_MIN ≈ 5th percentile of vital-article pairs (hard puzzle floor).
// SCORING_SIM_MAX ≈ a "very hot" hop — clearly close to the target.
// These are intentionally wider than any per-difficulty SIM_RANGE so that
// good navigation hops don't saturate at 100 before reaching the target.
export const SCORING_SIM_MIN = 0.40;
export const SCORING_SIM_MAX = 0.75;

const HUB_MULTIPLIER = 0.4;

export const SNIFF_BUDGETS = { easy: 3, medium: 3, hard: 2 };
export const SNIFF_PENALTIES = scoringParams.sniffPenalty;
export const SCOUT_BUDGETS = { easy: 1, medium: 2, hard: 2 };
export const SCOUT_PENALTIES = scoringParams.scoutPenalty;
export const SHOW_MORE_PENALTIES = scoringParams.showMorePenalty;
export const SIM_RANGES = scoringParams.simRanges;

/**
 * Hop score emojis — temperature/weather gradient based on normalized [0,1] score.
 * Thresholds tuned to the global [SCORING_SIM_MIN, SCORING_SIM_MAX] range:
 * the distribution peak (~0.47) normalizes to ~0.20, landing at the 💨 floor.
 */
const HOP_EMOJIS = [
  { min: 0.65, emoji: '\u{1F525}' },  // 🔥 top ~35%
  { min: 0.40, emoji: '\u{2600}\u{FE0F}' },  // ☀️ above-average
  { min: 0.20, emoji: '\u{1F4A8}' }, // 💨 average / lukewarm
  { min: 0.07, emoji: '\u{2744}\u{FE0F}' }, // ❄️ below average
  { min: 0.0,  emoji: '\u{1F9CA}' },  // 🧊 at/near floor
];

/**
 * Returns the emoji for a hop given its raw similarity and difficulty.
 * Normalizes similarity to [0,1] within the global scoring range before lookup.
 */
export function getHopEmoji(similarity, difficulty) {
  const norm = Math.max(0, Math.min(1, (similarity - SCORING_SIM_MIN) / (SCORING_SIM_MAX - SCORING_SIM_MIN)));
  for (const { min, emoji } of HOP_EMOJIS) {
    if (norm >= min) return emoji;
  }
  return '\u{1F9CA}';
}

/**
 * Compute the normalized score for a single hop.
 * Normalizes similarity to [0, 1] within the global scoring range,
 * then scales to [0, DIFFICULTY_MAX[difficulty]].
 */
export function hopScore(similarity, difficulty) {
  const norm = Math.max(0, Math.min(1, (similarity - SCORING_SIM_MIN) / (SCORING_SIM_MAX - SCORING_SIM_MIN)));
  return Math.round(norm * DIFFICULTY_MAX[difficulty]);
}

/**
 * Returns the hub penalty multiplier for a hop.
 * 0.4 if the article is a hub, 1.0 otherwise.
 */
export function hubMultiplier(title, difficulty) {
  return isHub(title, difficulty) ? HUB_MULTIPLIER : 1.0;
}

/**
 * Bonus points awarded per hop saved (unused hop).
 * Each hop saved earns a flat bonus that escalates.
 */
const HOP_SAVED_BASE = scoringParams.hopSavedBase ?? 15;
const HOP_SAVED_ESCALATION = scoringParams.hopSavedEscalation ?? 5;

export function hopSavedBonus(remainingHops) {
  let bonus = 0;
  for (let i = 0; i < remainingHops; i++) {
    bonus += HOP_SAVED_BASE + HOP_SAVED_ESCALATION * i;
  }
  return bonus;
}

/**
 * Compute final score from an array of hop records.
 * Each record: { title, similarity, isHub }
 */
export function finalScore(hops, maxHops, difficulty, won) {
  let total = 0;
  for (const hop of hops) {
    const raw = hopScore(hop.similarity, difficulty);
    const mult = hubMultiplier(hop.title, difficulty);
    total += Math.round(raw * mult);
  }
  if (won) {
    const remaining = maxHops - hops.length;
    total += hopSavedBonus(remaining);
  }
  return total;
}

/**
 * Generate shareable text for the end screen.
 */
export function generateShareText(difficulty, hops, score, won, startTitle, targetTitle, sniffsUsed = 0, scoutsUsed = 0) {
  const dateStr = getGameDateStr();
  const diffLabel = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
  const result = won ? `Trail complete!` : `Trail went cold`;

  const hopIcons = hops.map((h, i) => {
    return (won && i === hops.length - 1) ? '\u{1F40C}' : getHopEmoji(h.similarity, difficulty);
  }).join(' ');

  const hintParts = [];
  if (sniffsUsed > 0) hintParts.push(`${sniffsUsed} sniff${sniffsUsed > 1 ? 's' : ''}`);
  if (scoutsUsed > 0) hintParts.push(`${scoutsUsed} scout${scoutsUsed > 1 ? 's' : ''}`);
  const hintSuffix = hintParts.length > 0 ? ` (${hintParts.join(', ')})` : '';

  return [
    `\u{1F40C} snail's trail \u{2014} ${dateStr}`,
    `${diffLabel}: ${startTitle} \u{2192} ${targetTitle}`,
    '',
    hopIcons,
    '',
    `${result} in ${hops.length} hops \u{2014} Score: ${score}${hintSuffix}`,
  ].join('\n');
}
